In [1]:
import torch

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

## 2.1

In [2]:
# 0 is included, 12 is not
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
# arange 1, 13
x = torch.arange(1, 13)
print(x[0].dtype)
x

torch.int64


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# count number of elements
x.numel()

12

In [16]:
# tensor shape; length along each axis
torch.Size([12]), torch.Size(x)


(torch.Size([12]), torch.Size([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]))

In [17]:
torch.tensor((3, 3)).size()

torch.Size([2])

In [18]:
# reshape
X = x.reshape(3, 4)
X

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [19]:
# reshape and let it infer with -1
x.reshape(-1, 6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [20]:
# construct tensor of 0s
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
# construct with 1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [22]:
# torch randn

torch.randn(3, 4)

tensor([[ 0.5131, -0.5493,  0.2329, -0.5433],
        [-0.4912, -0.0704,  0.3495, -0.7086],
        [-0.7277, -1.5812, -0.5472,  1.9702]])

In [23]:
# manually construct tensors 
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### indexing and slicing

In [24]:
X

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [25]:
# slicing
X[-1], X[1:3]

(tensor([ 9, 10, 11, 12]),
 tensor([[ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]))

In [27]:
# overwriting specific
X[0, 0] = 99
X

tensor([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [28]:
# overwrite 1st row

X[1, :] = 69
X

tensor([[99,  2,  3,  4],
        [69, 69, 69, 69],
        [ 9, 10, 11, 12]])

### element wise operations

In [30]:
x

tensor([99,  2,  3,  4, 69, 69, 69, 69,  9, 10, 11, 12])

In [36]:
torch.exp(x)

tensor([       inf, 7.3891e+00, 2.0086e+01, 5.4598e+01, 9.2538e+29, 9.2538e+29,
        9.2538e+29, 9.2538e+29, 8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05])

In [34]:
import math 

x_list = x.tolist()

[math.exp(x) for x in x_list]

[9.889030319346946e+42,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236,
 9.253781725587787e+29,
 9.253781725587787e+29,
 9.253781725587787e+29,
 9.253781725587787e+29,
 8103.083927575384,
 22026.465794806718,
 59874.14171519782,
 162754.79141900392]

In [38]:
# addition, subtraction, multiplication, division and exponentiation can all be element-wise
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [39]:
# stacking tensors
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [41]:
X.shape, Y.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [42]:
# since its concat on row, expected is 6x4
torch.cat((X, Y), dim=0).shape

torch.Size([6, 4])

In [43]:
# since its concat on column, expected is 3x8
torch.cat((X, Y), dim=1).shape

torch.Size([3, 8])

In [44]:
# masking
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [45]:
X.sum()

tensor(66.)

In [46]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [48]:
X.sum(axis=0), X.sum(axis=1)

(tensor([12., 15., 18., 21.]), tensor([ 6., 22., 38.]))

In [49]:
X.sum().item()

66.0

### Broadcasting

In [51]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

a.shape, b.shape

(torch.Size([3, 1]), torch.Size([1, 2]))

In [56]:
# broadcast to 3x2 matrix

# 3, 1 --> 3, 2
a 

# create new column
# 0 0
# 1 1
# 2 2

tensor([[0],
        [1],
        [2]])

In [57]:
# 1, 2 --> 3, 2
b

# create two new rows
# 0 1 
# 0 1
# 0 1

tensor([[0, 1]])

In [52]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### saving memory

In [58]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [59]:
# inplace update
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4764047696
id(Z): 4764047696


In [60]:
before = id(X)
X += Y
id(X) == before

True

In [ ]:
# using += or [:] makes it inplace

In [61]:
# numpy conversion
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)